### ISSUE TITLE
Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v2.5-b383

### ISSUE THREAD

**Issue by ghost** [NavidK0/Carbon#115]
Sometimes when player teleport from world to world I got this error.

``` java
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.PlayerList.moveToWorld(PlayerList.java:583) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:512) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.teleport(CraftEntity.java:200) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215) [Multiverse-Core-2.5.jar:?]
        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335) [Multiverse-Core-2.5.jar:?]
        at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163) [Multiverse-Core-2.5.jar:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) [Multiverse-Core-2.5.jar:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-2.5.jar:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-2.5.jar:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897) [Multiverse-Core-2.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:148) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.convertMapsToSections(JsonConfiguration.java:115) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.loadFromString(JsonConfiguration.java:110) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(JsonConfiguration.java:184) ~[?:?]
        at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.<init>(EncodedJsonConfiguration.java:20) ~[?:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:77) ~[?:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:269) ~[?:?]
        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98) ~[?:?]
        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87) ~[?:?]
        at com.onarandombox.multiverseinventories.WorldChangeShareHandler.handle(WorldChangeShareHandler.java:33) ~[?:?]
        at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:56) ~[?:?]
        at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:183) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor295.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_20]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_20]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        ... 27 more
Caused by: java.lang.IllegalArgumentException: Specified class does not exist ('org.bukkit.craftbukkit.v1_7_R4.inventory.BannerMeta')
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:146) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.convertMapsToSections(JsonConfiguration.java:115) ~[?:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.loadFromString(JsonConfiguration.java:110) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(JsonConfiguration.java:184) ~[?:?]
        at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.<init>(EncodedJsonConfiguration.java:20) ~[?:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:77) ~[?:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:269) ~[?:?]
        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98) ~[?:?]
        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87) ~[?:?]
        at com.onarandombox.multiverseinventories.WorldChangeShareHandler.handle(WorldChangeShareHandler.java:33) ~[?:?]
        at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:56) ~[?:?]
        at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:183) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor295.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_20]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_20]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        ... 27 more
```

**Comment by Shevchik** [comment]
Okay i fixed it. Not exactly it, so you will have to delete this player info to avoid this error.
The issue was banner meta serializing as wrong class, so bukkit could deserialize it back.
Now it serializes as it should, but it won't fix already improperly serialized banners.
