### ISSUE TITLE
Banner meta data not preserved?

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#140]
Dev build 28. This error is being thrown when a player tries to open a virtual container with a banner in it. 

```
[08:29:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.5.1
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.IllegalArgumentException: Specified class does not exist ('org.bukkit.craftbukkit.v1_7_R4.inventory.BannerMeta')
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:153) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:148) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:149) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOtherVault(UUIDVaultManager.java:119) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOtherVault(VaultOperations.java:163) ~[?:?]
    at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    ... 13 more
```

**Comment by Shevchik** [comment]
You will have to delete old serialized data.
Explained here:
https://github.com/NavidK0/Carbon/issues/115
