### ISSUE TITLE
[Bug] null initializing Carbon v1.6

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#16]
Compiled as of commit https://github.com/NavidK0/Carbon/commit/a79192a6e2b44ee28c191816fd992ef18bc59596

Spigot with patch 20141001a.

```
[12:26:14] [Server thread/INFO]: [Carbon] Loading Carbon v1.6
[12:26:14] [Server thread/ERROR]: null initializing Carbon v1.6 (Is it up to date?)
java.lang.NullPointerException
    at net.o2gaming.carbon.reflection.Injector.fixItemStack(Injector.java:536) ~[?:?]
    at net.o2gaming.carbon.reflection.Injector.registerRecipes(Injector.java:501) ~[?:?]
    at net.o2gaming.carbon.Carbon.onLoad(Carbon.java:43) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
```

**Comment by NavidK0** [comment]
Added a null check. This should remove the error, but it'll probably leave a message stating which item stack is null.
