### ISSUE TITLE
Redstone comparators no longer output a signal to hoppers or chests.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#171]
Dev build 48. http://build.true-games.org/job/Carbon/48/
Removing Carbon, redstone comparators work again.

I believe this commit is the culprit? https://github.com/NavidK0/Carbon/commit/df6a623c4aba8117cde448fc61115ebf62467591

**Comment by Matmorcat** [comment]
Same. This happens to item frames as well with Carbon.
The comparators have to be manually updated (via a nearby block update or toggling the comparator to subtract mode and back.

I remember it working when I first added Carbon to the server (maybe one of the earlier builds). Now I run Build 43 and it doesn't work.

**Comment by Shevchik** [comment]
I'm not sure what you mean by outputting a signal to a chest, but i tried to fix.
Can you please make a vid explaining what you mean.

**Comment by mibby** [comment]
Sorry, I'm not entirely sure myself. Just forwarding what others on my server have informed me what broke recently within carbon. I'm assuming sending a redstone signal to/through the chest, as it would with hoppers or other redstone mechanics. I'll update and check if it is functional again.

**Comment by Shevchik** [comment]
Actually i probably found the reason. Navid should really learn to merge properly >_<.

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by mibby** [comment]
@Shevchik Latest dev build, version 53

```
[01:32:46] [Server thread/INFO]: java.lang.IllegalArgumentException: Can not set static net.minecraft.server.v1_7_R4.BlockRedstoneComparator field net.minecraft.server.v1_7_R4.Blocks.REDSTONE_COMPARATOR_OFF to com.lastabyss.carbon.blocks.BlockRedstoneComparator
[01:32:46] [Server thread/INFO]:    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[01:32:46] [Server thread/INFO]:    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[01:32:46] [Server thread/INFO]:    at sun.reflect.UnsafeStaticObjectFieldAccessorImpl.set(Unknown Source)
[01:32:46] [Server thread/INFO]:    at java.lang.reflect.Field.set(Unknown Source)
[01:32:46] [Server thread/INFO]:    at com.lastabyss.carbon.Injector.setStaticFinalField(Injector.java:664)
[01:32:46] [Server thread/INFO]:    at com.lastabyss.carbon.Injector.registerAll(Injector.java:618)
[01:32:46] [Server thread/INFO]:    at com.lastabyss.carbon.Carbon.onLoad(Carbon.java:96)
[01:32:46] [Server thread/INFO]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374)
[01:32:46] [Server thread/INFO]:    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152)
[01:32:46] [Server thread/INFO]:    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[01:32:46] [Server thread/INFO]:    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
```

**Comment by Shevchik** [comment]
Shii..

**Comment by Shevchik** [comment]
Should now work.

**Comment by mibby** [comment]
No more error on startup. :) Quickly testing, comparator seems to be lighting up when set next to a chest or hopper with an item in it. Signal off when no items are in either a chest or hopper.  I believe this is the intended behavior, confirming in singleplayer anyways. I'll get back to the players who reported it was broken to see if it is fixed with them.

**Comment by mibby** [comment]
Confirmed fixed.
