### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by tamasnorbert** [NavidK0/Carbon#201]
This was the error in console.....  What shall I do?
Newest Spigot , newest Carbon version..

[17:42:35] [Server thread/INFO]: Starting minecraft server version 1.7.10
[17:42:35] [Server thread/INFO]: Loading properties
[17:42:35] [Server thread/INFO]: Default game type: SURVIVAL
[17:42:35] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1544 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[17:42:35] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:42:35] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:42:35] [Server thread/INFO]: Generating keypair
[17:42:36] [Server thread/INFO]: Starting Minecraft server on _:25565
[17:42:36] [Server thread/INFO]: [Carbon] Loading Carbon v1.7
[17:42:36] [Server thread/INFO]: [Carbon] Server version git-Spigot-1544 (MC: 1.7.10) detected! Carbon is loading...
[17:42:36] [Server thread/INFO]: [Carbon] Lib folder has been set to plugins\Carbon\libraries\natives
[17:42:36] [Attach Listener/INFO]: [Carbon] Loaded transformer agent!
[17:42:36] [Attach Listener/INFO]: [Carbon] Transforming net/minecraft/server/v1_7_R4/DataWatcher
[17:42:36] [Attach Listener/INFO]: [Carbon] Transforming net/minecraft/server/v1_7_R4/EntityTracker
[17:42:36] [Attach Listener/INFO]: [Carbon] Transforming net/minecraft/server/v1_7_R4/EntityTrackerEntry
[17:42:36] [Attach Listener/INFO]: [Carbon] Transforming net/minecraft/server/v1_7_R4/DataWatcher
[17:42:36] [Attach Listener/INFO]: [Carbon] Transforming net/minecraft/server/v1_7_R4/EntityTracker
[17:42:36] [Attach Listener/INFO]: [Carbon] Transforming net/minecraft/server/v1_7_R4/EntityTrackerEntry
[17:42:36] [Attach Listener/INFO]: [Carbon] Transforming org/bukkit/craftbukkit/v1_7_R4/inventory/CraftItemStack
[17:42:36] [Attach Listener/INFO]: [Carbon] Transforming org/bukkit/craftbukkit/v1_7_R4/inventory/CraftMetaItem
[17:42:36] [Attach Listener/WARN]: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
[17:42:36] [Attach Listener/WARN]:  at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
[17:42:36] [Attach Listener/WARN]:  at sun.instrument.InstrumentationImpl.redefineClasses(Unknown Source)
[17:42:36] [Attach Listener/WARN]:  at com.lastabyss.carbon.instrumentation.CarbonTransformAgent.agentmain(CarbonTransformAgent.java:48)
[17:42:36] [Attach Listener/WARN]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:42:36] [Attach Listener/WARN]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:42:36] [Attach Listener/WARN]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:42:36] [Attach Listener/WARN]:  at java.lang.reflect.Method.invoke(Unknown Source)
[17:42:36] [Attach Listener/WARN]:  at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
[17:42:36] [Attach Listener/WARN]:  at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(Unknown Source)
[17:42:36] [Server thread/INFO]: [Carbon] Material SLIME with ID 165 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material BARRIER with ID 166 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material IRON_TRAPDOOR with ID 167 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material PRISMARINE with ID 168 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material SEA_LANTERN with ID 169 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material STANDING_BANNER with ID 176 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material WALL_BANNER with ID 177 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material DAYLIGHT_DETECTOR_INVERTED with ID 178 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material RED_SANDSTONE with ID 179 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material RED_SANDSTONE_STAIRS with ID 180 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material RED_SANDSTONE_DOUBLESLAB with ID 181 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material RED_SANDSTONE_SLAB with ID 182 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material SPRUCE_FENCE_GATE with ID 183 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material BIRCH_FENCE_GATE with ID 184 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material JUNGLE_FENCE_GATE with ID 185 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material DARK_OAK_FENCE_GATE with ID 186 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material ACACIA_FENCE_GATE with ID 187 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material SPRUCE_FENCE with ID 188 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material BIRCH_FENCE with ID 189 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material JUNGLE_FENCE with ID 190 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material DARK_OAK_FENCE with ID 191 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material ACACIA_FENCE with ID 192 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material SPRUCE_DOOR_BLOCK with ID 193 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material BIRCH_DOOR_BLOCK with ID 194 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material JUNGLE_DOOR_BLOCK with ID 195 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material ACACIA_DOOR_BLOCK with ID 196 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material DARK_OAK_DOOR_BLOCK with ID 197 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material PRISMARINE_SHARD with ID 409 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material PRISMARINE_CRYSTALS with ID 410 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material RABBIT with ID 411 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material COOKED_RABBIT with ID 412 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material RABBIT_STEW with ID 413 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material RABBIT_FOOT with ID 414 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material RABBIT_HIDE with ID 415 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material ARMOR_STAND with ID 416 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material MUTTON with ID 423 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material COOKED_MUTTON with ID 424 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material BANNER with ID 425 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material SPRUCE_DOOR with ID 427 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material BIRCH_DOOR with ID 428 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material JUNGLE_DOOR with ID 429 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material ACACIA_DOOR with ID 430 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Material DARK_OAK_DOOR with ID 431 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Entity ENDERMITE with ID 67 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Entity GUARDIAN with ID 68 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Entity RABBIT with ID 101 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] Entity ARMOR_STAND with ID 30 was injected into CraftBukkit.
[17:42:36] [Server thread/INFO]: [Carbon] DataWatcher type com.lastabyss.carbon.entity.ArmorStandPose was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block stone(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block sponge(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block stone_button(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block torch(Torch) with item tile.torch was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block stone_pressure_plate(Pressure Plate) with item tile.pressurePlate was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block wooden_pressure_plate(Pressure Plate) with item tile.pressurePlate was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block unlit_redstone_torch(Redstone Torch) with item tile.notGate was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block redstone_torch(Redstone Torch) with item tile.notGate was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block wooden_button(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block light_weighted_pressure_plate(Weighted Pressure Plate (Light)) with item tile.weightedPlate_light was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block heavy_weighted_pressure_plate(Weighted Pressure Plate (Heavy)) with item tile.weightedPlate_heavy was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block daylight_detector(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block slime(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block barrier(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block iron_trapdoor(tile.iron_trapdoor.name) with item tile.iron_trapdoor was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block prismarine(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block sea_lantern(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block standing_banner was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block wall_banner was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block daylight_detector_inverted was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block red_sandstone(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block red_sandstone_stairs(tile.red_sandstone_stairs.name) with item tile.red_sandstone_stairs was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block double_stone_slab2(tile.stoneSlab2.name) with item tile.stoneSlab2 was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block stone_slab2(tile.stoneSlab2.name) with item tile.stoneSlab2 was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block spruce_fence_gate(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block birch_fence_gate(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block jungle_fence_gate(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block dark_oak_fence_gate(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block acacia_fence_gate(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block spruce_fence(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block birch_fence(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block jungle_fence(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block dark_oak_fence(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block acacia_fence(tile.null.name) with item tile.null was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block spruce_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item spruce_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block birch_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item birch_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block jungle_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item jungle_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block acacia_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item acacia_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block dark_oak_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item dark_oak_door was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block anvil(Anvil) with item tile.anvil was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block enchanting_table(Enchantment Table) with item tile.enchantmentTable was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block chest(Chest) with item tile.chest was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Block trapped_chest(Chest) with item tile.chest was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item prismarine_shard was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item prismarine_crystals was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item rabbit was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item cooked_rabbit was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item rabbit_stew was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item rabbit_foot was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item rabbit_hide was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item mutton was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item cooked_mutton was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item banner was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Item armor_stand was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Entity com.lastabyss.carbon.entity.EntityEndermite was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Entity com.lastabyss.carbon.entity.EntityGuardian was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Entity com.lastabyss.carbon.entity.EntityRabbit was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Entity com.lastabyss.carbon.entity.EntityArmorStand was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Tile Entity com.lastabyss.carbon.entity.TileEntityBanner was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Tile Entity com.lastabyss.carbon.entity.TileEntityOptimizedChest was registered into Minecraft.
[17:42:36] [Server thread/INFO]: [Carbon] Packet com.lastabyss.carbon.packets.PacketPlayOutWorldBorder was registered into Minecraft with ID: 68
[17:42:36] [Server thread/INFO]: [Carbon] Packet com.lastabyss.carbon.packets.PacketPlayInUseEntity was registered into Minecraft with ID: 2
[17:42:36] [Server thread/ERROR]: org/spigotmc/SpigotDebreakifier initializing Carbon v1.7 (Is it up to date?)
java.lang.NoClassDefFoundError: org/spigotmc/SpigotDebreakifier
    at com.lastabyss.carbon.Injector.registerSpigotDebreakifierAddition(Injector.java:373) ~[?:?]
    at com.lastabyss.carbon.Injector.registerAll(Injector.java:479) ~[?:?]
    at com.lastabyss.carbon.Carbon.onLoad(Carbon.java:96) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374) [spigot.jar:git-Spigot-1544]
    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1544]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1544]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1544]
Caused by: java.lang.ClassNotFoundException: org.spigotmc.SpigotDebreakifier
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_51]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_51]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_51]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_51]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[spigot.jar:git-Spigot-1544]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[spigot.jar:git-Spigot-1544]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_51]
    ... 7 more
[17:42:36] [Server thread/INFO]: [Carbon] Enabling Carbon v1.7
[17:42:37] [Server thread/INFO]: ProtocolLib not found, not hooking. 1.7 clients not supported. ProtocolBlocker will kick clients only after full join.
[17:42:37] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "protocol"
[17:42:37] [Server thread/WARN]:    at java.lang.NumberFormatException.forInputString(Unknown Source)
[17:42:37] [Server thread/WARN]:    at java.lang.Integer.parseInt(Unknown Source)
[17:42:37] [Server thread/WARN]:    at java.lang.Integer.parseInt(Unknown Source)
[17:42:37] [Server thread/WARN]:    at com.lastabyss.carbon.protocolblocker.ProtocolBlocker.loadConfig(ProtocolBlocker.java:37)
[17:42:37] [Server thread/WARN]:    at com.lastabyss.carbon.Carbon.onEnable(Carbon.java:149)
[17:42:37] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[17:42:37] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
[17:42:37] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:42:37] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[17:42:37] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[17:42:37] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:153)
[17:42:37] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[17:42:37] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[17:42:37] [Server thread/INFO]: Carbon is enabled.
[17:42:37] [Server thread/INFO]: *_*\* Beginning UUID conversion, this may take A LONG time ****
[17:42:37] [Server thread/INFO]: Preparing level "world"
[17:42:37] [Server thread/INFO]: -------- World Settings For [world] --------
[17:42:37] [Server thread/INFO]: Item Despawn Rate: 6000
[17:42:37] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:42:37] [Server thread/INFO]: View Distance: 10
[17:42:37] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:42:37] [Server thread/INFO]: Clear tick list: false
[17:42:37] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:42:37] [Server thread/INFO]: Item Merge Radius: 2.5
[17:42:37] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:42:37] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:42:37] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:42:37] [Server thread/INFO]: Sending up to 5 chunks per packet
[17:42:37] [Server thread/INFO]: Max Entity Collisions: 8
[17:42:37] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:42:37] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:42:37] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:42:37] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:42:37] [Server thread/INFO]: Structure Info Saving: true
[17:42:37] [Server thread/INFO]: Random Lighting Updates: false
[17:42:37] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:42:37] [Server thread/INFO]: Mob Spawn Range: 4
[17:42:37] [Server thread/INFO]: Anti X-Ray: true
[17:42:37] [Server thread/INFO]:    Engine Mode: 1
[17:42:37] [Server thread/INFO]:    Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:42:37] [Server thread/INFO]:    Replace Blocks: [1, 5]
[17:42:37] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[17:42:37] [Server thread/INFO]: Item Despawn Rate: 6000
[17:42:37] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:42:37] [Server thread/INFO]: View Distance: 10
[17:42:37] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:42:37] [Server thread/INFO]: Clear tick list: false
[17:42:37] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:42:37] [Server thread/INFO]: Item Merge Radius: 2.5
[17:42:37] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:42:37] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:42:37] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:42:37] [Server thread/INFO]: Sending up to 5 chunks per packet
[17:42:37] [Server thread/INFO]: Max Entity Collisions: 8
[17:42:37] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:42:37] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:42:37] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:42:37] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:42:37] [Server thread/INFO]: Structure Info Saving: true
[17:42:37] [Server thread/INFO]: Random Lighting Updates: false
[17:42:37] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:42:37] [Server thread/INFO]: Mob Spawn Range: 4
[17:42:37] [Server thread/INFO]: Anti X-Ray: true
[17:42:37] [Server thread/INFO]:    Engine Mode: 1
[17:42:37] [Server thread/INFO]:    Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:42:37] [Server thread/INFO]:    Replace Blocks: [1, 5]
[17:42:37] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[17:42:37] [Server thread/INFO]: Item Despawn Rate: 6000
[17:42:37] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:42:37] [Server thread/INFO]: View Distance: 10
[17:42:37] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:42:37] [Server thread/INFO]: Clear tick list: false
[17:42:37] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:42:37] [Server thread/INFO]: Item Merge Radius: 2.5
[17:42:37] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:42:37] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:42:37] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:42:37] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:42:37] [Server thread/INFO]: Sending up to 5 chunks per packet
[17:42:37] [Server thread/INFO]: Max Entity Collisions: 8
[17:42:37] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:42:37] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:42:37] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:42:37] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:42:37] [Server thread/INFO]: Structure Info Saving: true
[17:42:37] [Server thread/INFO]: Random Lighting Updates: false
[17:42:37] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:42:37] [Server thread/INFO]: Mob Spawn Range: 4
[17:42:37] [Server thread/INFO]: Anti X-Ray: true
[17:42:37] [Server thread/INFO]:    Engine Mode: 1
[17:42:37] [Server thread/INFO]:    Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:42:37] [Server thread/INFO]:    Replace Blocks: [1, 5]
[17:42:37] [Server thread/INFO]: Preparing start region for level 0 (Seed: -4250041763465820768)
[17:42:37] [Server thread/INFO]: Preparing start region for level 1 (Seed: -4250041763465820768)
[17:42:37] [Server thread/INFO]: Preparing start region for level 2 (Seed: -4250041763465820768)
[17:42:37] [Server thread/INFO]: [Carbon] Editing world: world
[17:42:37] [Server thread/INFO]: [Carbon] Adding populator for world: world
[17:42:37] [Server thread/INFO]: [Carbon] Done editing world: world
[17:42:37] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:42:37] [Server thread/INFO]: Done (0.491s)! For help, type "help" or "?"
[17:42:37] [Server thread/INFO]: Stopping server
[17:42:37] [Server thread/INFO]: [Carbon] Disabling Carbon v1.7
[17:42:37] [Server thread/INFO]: Saving players
[17:42:37] [Server thread/INFO]: Saving worlds
[17:42:37] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[17:42:37] [Server thread/INFO]: Saving chunks for level 'world_nether'/Nether
[17:42:37] [Server thread/INFO]: Saving chunks for level 'world_the_end'/The End
[17:42:37] [Thread-4/INFO]: Stopping server
[17:42:37] [Thread-4/INFO]: Saving players
[17:42:37] [Thread-4/INFO]: Saving worlds
[17:42:37] [Thread-4/INFO]: Saving chunks for level 'world'/Overworld

**Comment by Shevchik** [comment]
Carbon is no longer supported.

**Comment by Jikoo** [comment]
> Spigot-1544

Your Spigot is INCREDIBLY outdated. Did you read the readme at all? 1649 was the last pre-DMCA, and you need post-DMCA patched builds for Carbon.

**Comment by tamasnorbert** [comment]
First of all i don't know how to download it... because when i click on the link..    

![image](https://cloud.githubusercontent.com/assets/9989127/5230575/da0fb5a0-7730-11e4-89ce-5f99c8937484.png)

here.. this page comes in 
![image](https://cloud.githubusercontent.com/assets/9989127/5230567/be16017e-7730-11e4-9146-0237ec767db2.png) and from here i don't know what to do...
