### ISSUE TITLE
[Error] java.lang.NullPointerException at com.lastabyss.carbon.protocolmodifier.ProtocolBlockListener

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#52]
Compiled source as of commit https://github.com/NavidK0/Carbon/commit/5dffb7c7e1e83ed1d1be6f4637829a04dfdaf9cd

Error on startup.

```
[20:41:27] [Server thread/INFO]: [Carbon] Enabling Carbon v1.6
[20:41:27] [Server thread/WARN]: java.lang.NullPointerException
[20:41:27] [Server thread/WARN]:    at com.lastabyss.carbon.protocolmodifier.ProtocolBlockListener.<init>(ProtocolBlockListener.java:28)
[20:41:27] [Server thread/WARN]:    at com.lastabyss.carbon.Carbon.onEnable(Carbon.java:103)
[20:41:27] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[20:41:27] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[20:41:27] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[20:41:27] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[20:41:27] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[20:41:27] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
[20:41:27] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
[20:41:27] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
[20:41:27] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
[20:41:27] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[20:41:27] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[20:41:27] [Server thread/INFO]: Carbon is enabled.
```

**Comment by Jikoo** [comment]
Did you make sure your config.yml has the correct entries? Would be safer to have defaults specified in the methods, but not required.

**Comment by mibby** [comment]
Yes. I specifically made sure the config had been updated as of the last commit.

```
options:
    sheep:
        dropMutton: true
    creeper:
        dropMobHead: true
    barrierTranslateID: 20
    worlds: [world]

protocollib:
    blocks:
        slime: 133
        barrier: 20
        iron_trapdoor: 96
        prismarine: 48
        sea_lantern: 89
        standing_banner: 63
        wall_banner: 68
        red_sandstone: 24
        red_sandstone_stairs: 128
        red_sandstone_doubleslab: 43
        red_sandstone_slab: 44
        fence_gates: 107
        fences: 85
        doors: 64
    entities:
        silverfish: 60
        endermites: 94
        rabbits: 93
    items:
        slime: 133
        barrier: 7
        iron_trapdoor: 96
        prismarine: 48
        sea_lantern: 89
        red_sandstone: 24
        red_sandstone_stairs: 128
        red_sandstone_doubleslab: 43
        red_sandstone_slab: 44
        fence_gates: 107
        fences: 85
        doors: 324
        rabbit_meat: 365
        rabbit_cooked_meat: 366
        rabbit_stew: 282
        mutton: 365
        cooked_mutton: 366
        banner: 323
        prismarine_shard: 1
        prismarine_crystal: 1
        rabbit_foot: 1
        rabbit_hide: 1
        armor_stand: 1


donottouch.configVersion: 0.3
```

```
'4': You cannot log on this server with version 1.7.9! Please upgrade to 1.8!
'5': You cannot log on this server with version 1.7.10! Please upgrade to 1.8!
```

**Comment by mibby** [comment]
Fixed via commit https://github.com/NavidK0/Carbon/commit/249a0ac21071ee09711c2b574c5aa7b6c012e773
