### ISSUE TITLE
Could not pass event EntityDeathEvent to Carbon 

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#95]
Compiled as of commit https://github.com/NavidK0/Carbon/commit/f8a96041041590010ce4d2039069cd31e65379cc

```
[17:31:15] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Carbon v1.6.4
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:379) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityLiving.die(EntityLiving.java:810) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityAnimal.damageEntity(SourceFile:145) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityWolf.damageEntity(EntityWolf.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.damage(CraftLivingEntity.java:203) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.damage(CraftLivingEntity.java:188) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at com.gmail.nossr50.util.skills.CombatUtils.dealDamage(CombatUtils.java:377) [mcMMO.jar:?]
    at com.gmail.nossr50.skills.taming.TrackedTamingEntity.run(TrackedTamingEntity.java:52) [mcMMO.jar:?]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
    at com.lastabyss.carbon.listeners.ItemListener.onCreeperDeath(ItemListener.java:90) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor479.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_20]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_20]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    ... 19 more
```

**Comment by Wombosvideo** [comment]
Probably an error occuring related to #82

**Comment by Byteflux** [comment]
This also happens when you use /kill or /suicide in Essentials.

**Comment by NavidK0** [comment]
Fixed with commit:
https://github.com/NavidK0/Carbon/commit/881272aa0b8e4a7cb17fa1c752cca01bcb5666f0
